import type { BaseballCardProject, BudgetItem } from './types';

// Seed data from (3.9.26) Master Tracker.xlsx — PROD Tasks sheet
export const SEED_PROJECTS: BaseballCardProject[] = [
  {
    id: 'task-01',
    name: 'Add Kaiser networks',
    description: 'Add Kaiser networks for v8. QC. Finalize in v9',
    people: [
      { id: 'p-david', name: 'David', role: 'Accountable' },
      { id: 'p-chris', name: 'Chris', role: 'Responsible' },
      { id: 'p-andy-1', name: 'Andy', role: 'Responsible' },
      { id: 'p-bobby-1', name: 'Bobby', role: 'Contributor' },
      { id: 'p-kalvig-1', name: 'Kalvig', role: 'Contributor' },
      { id: 'p-peter-1', name: 'Peter', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'urgent',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: '2026-03-01',
    tags: ['v8', 'networks'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'In Production',
    mma_priority: 'Very High',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'David',
    mma_responsible: 'Chris, Andy',
    mma_contributor: 'Bobby, Kalvig',
    mma_informed: 'Peter',
    mma_estimated_turn_time: '2026-03-01',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-02',
    name: 'Add Cigna Third Party Networks',
    description: 'Priority Health, Health Partners',
    people: [
      { id: 'p-hart-2', name: 'Hart', role: 'Accountable' },
      { id: 'p-hart-2r', name: 'Hart', role: 'Responsible' },
      { id: 'p-bobby-2', name: 'Bobby', role: 'Contributor' },
      { id: 'p-peter-2', name: 'Peter', role: 'Informed' },
      { id: 'p-david-2', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Enhancements',
    priority: 'urgent',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'networks', 'cigna'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'In Production',
    mma_priority: 'Very High',
    mma_contract_ref: 'Schedule E - Enhancements',
    mma_accountable: 'Hart',
    mma_responsible: 'Hart',
    mma_contributor: 'Bobby',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-03',
    name: 'Billing Code Type Analysis & Expansion',
    description: '% negotiated type passed through from carrier field for conversions (implement an approach for POC calcs), CSTM-00 review, APR-DRG review (starting with BCBS MN). This is a carrier rate pass through. Unsure whether or not that can happen this round because the team needs to determine methods/approach.',
    people: [
      { id: 'p-bobby-3a', name: 'Bobby', role: 'Accountable' },
      { id: 'p-kalvig-3', name: 'Kalvig', role: 'Responsible' },
      { id: 'p-andy-3', name: 'Andy', role: 'Responsible' },
      { id: 'p-jenna-3', name: 'Jenna', role: 'Contributor' },
      { id: 'p-peter-3', name: 'Peter', role: 'Informed' },
      { id: 'p-david-3', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'urgent',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'billing-codes', 'methods'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'Set for Methods Sprint',
    mma_priority: 'Very High',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'Bobby',
    mma_responsible: 'Kalvig, Andy',
    mma_contributor: 'Jenna',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: "Negotiated type that's a percentage, versus the rate itself. We have the data, but need to convert it to a rate that can be used downstream in IRIS.",
    mma_date: '2026-02-15',
  },
  {
    id: 'task-04',
    name: 'APR-DRG Adjustment',
    description: 'MN, SD, and IA show rates in APR-DRG. We need a way to populate the APR-DRG as well as the MS-DRGs. This needs to be advanced for v8, but finalized for v9 at the latest.',
    people: [
      { id: 'p-bobby-4a', name: 'Bobby', role: 'Accountable' },
      { id: 'p-kalvig-4', name: 'Kalvig', role: 'Responsible' },
      { id: 'p-andy-4', name: 'Andy', role: 'Responsible' },
      { id: 'p-jenna-4', name: 'Jenna', role: 'Contributor' },
      { id: 'p-peter-4', name: 'Peter', role: 'Informed' },
      { id: 'p-david-4', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Enhancements',
    priority: 'urgent',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'apr-drg', 'methods'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'Set for Methods Sprint',
    mma_priority: 'Very High',
    mma_contract_ref: 'Schedule E - Enhancements',
    mma_accountable: 'Bobby',
    mma_responsible: 'Kalvig, Andy',
    mma_contributor: 'Jenna',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-05',
    name: 'Taxonomy Flag Expansion',
    description: 'Add a care steerage taxonomy flag expansion to other high-volume OP. Needs to be implemented in v8.',
    people: [
      { id: 'p-bobby-5a', name: 'Bobby', role: 'Accountable' },
      { id: 'p-andy-5', name: 'Andy', role: 'Responsible' },
      { id: 'p-kalvig-5', name: 'Kalvig', role: 'Contributor' },
      { id: 'p-peter-5', name: 'Peter', role: 'Informed' },
      { id: 'p-david-5', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'urgent',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'taxonomy'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'In Production',
    mma_priority: 'Very High',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'Bobby',
    mma_responsible: 'Andy',
    mma_contributor: 'Kalvig',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-06',
    name: '2.0 Files',
    description: 'Processors are built and have been tested to run 2.0 schemas. Hold on this task until we begin production on v9.',
    people: [
      { id: 'p-hart-6a', name: 'Hart', role: 'Accountable' },
      { id: 'p-hart-6r', name: 'Hart', role: 'Responsible' },
      { id: 'p-shammas-6', name: 'Shammas', role: 'Contributor' },
      { id: 'p-david-6', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'urgent',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v9', '2.0-schema'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v9',
    mma_status: 'Confirming Completion',
    mma_priority: 'Very High',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'Hart',
    mma_responsible: 'Hart',
    mma_contributor: 'Shammas',
    mma_informed: 'David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-07',
    name: 'Blue HPN, Blue Select',
    description: 'TBD',
    people: [],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'high',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v9', 'pre-data-order'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v9',
    mma_status: 'Pre-Data Order',
    mma_priority: 'High',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'TBD',
    mma_responsible: 'TBD',
    mma_contributor: 'TBD',
    mma_informed: 'TBD',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-08',
    name: 'Other HPAs, MVP (Upstate & Western NY), other regionals',
    description: '[Break this category out when we have details]',
    people: [],
    status: 'active',
    category: 'Schedule E - Enhancements',
    priority: 'high',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v9-11', 'pre-data-order', 'regionals'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v9 - 11',
    mma_status: 'Pre-Data Order',
    mma_priority: 'High',
    mma_contract_ref: 'Schedule E - Enhancements',
    mma_accountable: 'TBD',
    mma_responsible: 'TBD',
    mma_contributor: 'TBD',
    mma_informed: 'TBD',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-09',
    name: 'Professional Rates Reviewed from Hospital MRFs (starting with SC)',
    description: 'High importance (SC market launching). Big change in the professional coverage threshold in the v7. (Rates also needed for Promise).',
    people: [
      { id: 'p-bobby-9a', name: 'Bobby', role: 'Accountable' },
      { id: 'p-kalvig-9', name: 'Kalvig', role: 'Responsible' },
      { id: 'p-andy-9', name: 'Andy', role: 'Responsible' },
      { id: 'p-jenna-9', name: 'Jenna', role: 'Contributor' },
      { id: 'p-peter-9', name: 'Peter', role: 'Informed' },
      { id: 'p-david-9', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'high',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'hospital-mrf', 'sc-market'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'In Queue',
    mma_priority: 'High',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'Bobby',
    mma_responsible: 'Kalvig, Andy',
    mma_contributor: 'Jenna',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-10',
    name: 'Secondary NPI Verification',
    description: 'Focus on "priority" states for hospital MRF processing and mapping.',
    people: [
      { id: 'p-bobby-10a', name: 'Bobby', role: 'Accountable' },
      { id: 'p-jenna-10', name: 'Jenna/Kalvig', role: 'Responsible (Processing)' },
      { id: 'p-jenna-10m', name: 'Jenna/Bobby/Kalvig', role: 'Responsible (Mapping)' },
      { id: 'p-peter-10', name: 'Peter', role: 'Informed' },
      { id: 'p-david-10', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'TBD',
    priority: 'high',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'npi', 'hospital-mrf'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'Unknown',
    mma_priority: 'High',
    mma_contract_ref: 'TBD',
    mma_accountable: 'Bobby',
    mma_responsible: 'Jenna/Kalvig (Processing); Jenna/Bobby/Kalvig (Mapping)',
    mma_contributor: 'N/A',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-11',
    name: 'Add Kaiser Networks (State Expansion)',
    description: 'Primary states for new Kaiser networks are: CA, CO, GA, HI, MD, OR, VA, WA, and DC',
    people: [
      { id: 'p-bobby-11a', name: 'Bobby', role: 'Accountable' },
      { id: 'p-kalvig-11', name: 'Kalvig', role: 'Responsible' },
      { id: 'p-bobby-11r', name: 'Bobby', role: 'Responsible' },
      { id: 'p-andy-11', name: 'Andy', role: 'Contributor' },
      { id: 'p-jenna-11', name: 'Jenna', role: 'Contributor' },
      { id: 'p-peter-11', name: 'Peter', role: 'Informed' },
      { id: 'p-david-11', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'medium',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'kaiser', 'states'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'Data is in PP',
    mma_priority: 'Medium',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'Bobby',
    mma_responsible: 'Kalvig, Bobby',
    mma_contributor: 'Andy, Jenna',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-12',
    name: 'Metropolitan Divisions',
    description: 'GEO EXP #2. Further geographic expansion in v9. Peter needs to help us unpack this.',
    people: [],
    status: 'active',
    category: 'TBD',
    priority: 'medium',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v9-v10', 'geo-expansion'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v9 - v10',
    mma_status: 'In Queue',
    mma_priority: 'Medium',
    mma_contract_ref: 'TBD',
    mma_accountable: 'TBD',
    mma_responsible: 'TBD',
    mma_contributor: 'TBD',
    mma_informed: 'TBD',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-13',
    name: 'Balance of State',
    description: 'GEO EXP #3.',
    people: [],
    status: 'active',
    category: 'TBD',
    priority: 'medium',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v9-v10', 'geo-expansion'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v9 - v10',
    mma_status: 'In Queue',
    mma_priority: 'Medium',
    mma_contract_ref: 'TBD',
    mma_accountable: 'TBD',
    mma_responsible: 'TBD',
    mma_contributor: 'TBD',
    mma_informed: 'TBD',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-14',
    name: 'BCBS PPO Mapping',
    description: 'GEO EXP #1. Proceed with BCBS PPO mapping to enable broader geographic selection logic in the UI - micropolitan implementation in v8 (metro-divisions and balance of state for later version release).',
    people: [
      { id: 'p-hart-14a', name: 'Hart', role: 'Accountable' },
      { id: 'p-hart-14r', name: 'Hart', role: 'Responsible' },
      { id: 'p-bobby-14', name: 'Bobby', role: 'Contributor' },
      { id: 'p-peter-14', name: 'Peter', role: 'Informed' },
      { id: 'p-david-14', name: 'David', role: 'Informed' },
    ],
    status: 'active',
    category: 'Schedule E - Core',
    priority: 'medium',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'geo-expansion', 'bcbs'],
    archived_at: null,
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'Confirming Completion',
    mma_priority: 'Medium',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'Hart',
    mma_responsible: 'Hart',
    mma_contributor: 'Bobby',
    mma_informed: 'Peter, David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-15',
    name: 'Water Filtration Companion Materials',
    description: 'Share re-branded water filtration outline',
    people: [
      { id: 'p-david-15a', name: 'David', role: 'Accountable' },
      { id: 'p-topher-15', name: 'Topher', role: 'Responsible' },
      { id: 'p-peter-15', name: 'Peter', role: 'Contributor' },
      { id: 'p-peter-15i', name: 'Peter', role: 'Informed' },
    ],
    status: 'archived',
    category: 'Schedule E - Core',
    priority: 'low',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v8', 'complete'],
    archived_at: '2026-02-15T00:00:00.000Z',
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v8',
    mma_status: 'Complete',
    mma_priority: 'Low',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'David',
    mma_responsible: 'Topher',
    mma_contributor: 'Peter',
    mma_informed: 'Peter',
    mma_estimated_turn_time: '8 Days',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-16',
    name: 'Analytic Tests Output',
    description: 'Create data output "analytic tests" (Detroit MSA NetNav vs. Turquoise (move coverage/v7 20 percent left to close)',
    people: [
      { id: 'p-bobby-16a', name: 'Bobby/Jeremy', role: 'Accountable' },
      { id: 'p-andy-16', name: 'Andy/Peter', role: 'Responsible' },
      { id: 'p-cheryl-16', name: 'Cheryl', role: 'Contributor' },
      { id: 'p-david-16', name: 'David', role: 'Informed' },
    ],
    status: 'archived',
    category: 'TBD',
    priority: 'low',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v7'],
    archived_at: '2026-02-15T00:00:00.000Z',
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v7',
    mma_status: 'TBD',
    mma_priority: 'Low',
    mma_contract_ref: 'TBD',
    mma_accountable: 'Bobby/Jeremy',
    mma_responsible: 'Andy/Peter',
    mma_contributor: 'Cheryl',
    mma_informed: 'David',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
  {
    id: 'task-17',
    name: 'Regional Network List',
    description: 'Send a list of the regional networks available and in queue for v8/v9',
    people: [
      { id: 'p-david-17a', name: 'David', role: 'Accountable' },
      { id: 'p-hart-17', name: 'Hart', role: 'Responsible' },
      { id: 'p-andy-17', name: 'Andy', role: 'Contributor' },
      { id: 'p-peter-17', name: 'Peter', role: 'Informed' },
    ],
    status: 'archived',
    category: 'Schedule E - Core',
    priority: 'low',
    pinned: false,
    manual_rank: null,
    last_activity_at: '2026-02-15T00:00:00.000Z',
    created_at: '2026-02-15T00:00:00.000Z',
    target_date: null,
    tags: ['v7', 'done'],
    archived_at: '2026-02-15T00:00:00.000Z',
    tasks: [],
    notes: [],
    links: [],
    mma_version: 'v7',
    mma_status: 'Done',
    mma_priority: 'Low',
    mma_contract_ref: 'Schedule E - Core',
    mma_accountable: 'David',
    mma_responsible: 'Hart',
    mma_contributor: 'Andy',
    mma_informed: 'Peter',
    mma_estimated_turn_time: '',
    mma_comments: '',
    mma_date: '2026-02-15',
  },
];

// Schedule E — Data Enhancements
export const SCHEDULE_E_ITEMS: BudgetItem[] = [
  {
    id: 'ewo-1',
    ewoNumber: 'EWO-1',
    projectId: 'PAD 25-03-MMA-APRDRG',
    description: 'APR-DRG/EAPG to MS-DRG Conversion — BCBS Plans (MN, ND, IA, SD)',
    approvedBudget: 28236,
    //              Jan    Feb     Mar     Apr     May     Jun  Jul  Aug  Sep  Oct  Nov  Dec
    monthlyAllocations: [0, 7059, 7059, 7059, 7059, 0, 0, 0, 0, 0, 0, 0],
    poolBalance: 121764,
  },
  {
    id: 'ewo-2',
    ewoNumber: 'EWO-2',
    projectId: 'PAD 25-03-MMA-REGNET1',
    description: 'Regional Network Additions — Cigna HealthPartners & Priority Health (v8)',
    approvedBudget: 10000,
    monthlyAllocations: [0, 10000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    poolBalance: 111764,
  },
  {
    id: 'ewo-3',
    ewoNumber: 'EWO-3',
    projectId: 'PAD 25-03-MMA-REGNET2',
    description: 'Regional Carrier Expansion Batch 2 — 18 Networks (v9)',
    approvedBudget: 90000,
    monthlyAllocations: [0, 0, 0, 30000, 30000, 30000, 0, 0, 0, 0, 0, 0],
    poolBalance: 21764,
  },
  {
    id: 'ewo-4',
    ewoNumber: 'EWO-4',
    projectId: 'PAD 25-03-MMA-NETENH',
    description: 'Network File Enhancement — Key Payer Data Integrity (Cigna + UHC, 10 Networks, v9)',
    approvedBudget: 15000,
    monthlyAllocations: [0, 0, 0, 5000, 5000, 5000, 0, 0, 0, 0, 0, 0],
    poolBalance: 6764,
  },
];

// Schedule F — Data Innovation
export const SCHEDULE_F_ITEMS: BudgetItem[] = [
  {
    id: 'iwo-1',
    ewoNumber: 'IWO-1',
    projectId: 'PAD-25-04-MMA-HRE',
    description: 'Hospital Client Growth Opportunity — Provider MRF Expansion & Delivery Tools',
    approvedBudget: 100000,
    monthlyAllocations: [50000, 50000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    poolBalance: 700000,
  },
  {
    id: 'iwo-2',
    ewoNumber: 'IWO-2',
    projectId: 'PAD-25-04-MMA-DRU',
    description: 'Pharmacy Data Analytics Discovery & Mapping — J-Code Analysis & Strategic Framing',
    approvedBudget: 100000,
    monthlyAllocations: [0, 50000, 50000, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    poolBalance: 600000,
  },
  {
    id: 'iwo-3',
    ewoNumber: 'IWO-3',
    projectId: 'PAD 25-04-MMA-CLMTIC',
    description: 'Claims-TiC Data Linkage & Repricing Model — MMA Independent Repricing by Q3 2026',
    approvedBudget: 51738,
    monthlyAllocations: [0, 0, 12935, 12935, 12934, 12934, 0, 0, 0, 0, 0, 0],
    poolBalance: 548262,
  },
  {
    id: 'iwo-4',
    ewoNumber: 'IWO-4',
    projectId: 'PAD 25-04-MMA-EPI',
    description: 'Episode Intelligence — AI-Augmented Analytics Platform & June Global Meeting Demo',
    approvedBudget: 125000,
    monthlyAllocations: [0, 0, 0, 41667, 41667, 41666, 0, 0, 0, 0, 0, 0],
    poolBalance: 387513,
  },
  {
    id: 'iwo-5',
    ewoNumber: 'IWO-5',
    projectId: 'PAD 25-04-MMA-SPRX',
    description: 'Specialty Rx Data Analytics Discovery & Modeling — Site-of-Care Variance & High-Cost Drug Analysis',
    approvedBudget: 35749,
    monthlyAllocations: [0, 0, 17875, 17874, 0, 0, 0, 0, 0, 0, 0, 0],
    poolBalance: 512513,
  },
  {
    id: 'iwo-6',
    ewoNumber: 'IWO-6',
    projectId: 'PAD 25-04-MMA-QUAL',
    description: 'Quality Measure Methods & Data Pipeline Assimilation — Cost-Quality Pairing for Starset v10',
    approvedBudget: 138775,
    monthlyAllocations: [0, 0, 0, 46258, 46258, 46259, 0, 0, 0, 0, 0, 0],
    poolBalance: 248738,
  },
  {
    id: 'iwo-7',
    ewoNumber: 'IWO-7',
    projectId: 'PAD 25-04-MMA-PLTF',
    description: 'Next-Gen Analytics Platform — Architecture & Prototyping (6 Modules; Design Only)',
    approvedBudget: 32350,
    monthlyAllocations: [0, 0, 0, 0, 10784, 10783, 10783, 0, 0, 0, 0, 0],
    poolBalance: 216388,
  },
];

export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
export const SCHEDULE_E_POOL_START = 150000;
export const SCHEDULE_E_TOTAL_ALLOCATED = 143236;
export const SCHEDULE_F_POOL_START = 800000;
export const SCHEDULE_F_TOTAL_ALLOCATED = 583612;
