-- CCM schema migration v9 Jul15
-- Apply in Supabase SQL editor

DROP TABLE IF EXISTS ccm_region CASCADE;
CREATE TABLE ccm_region (
  id BIGSERIAL PRIMARY KEY,
  region_mma BIGINT,
  region_name_mma TEXT,
  region_label_mma TEXT,
  carrier TEXT,
  plan_ids TEXT,
  carrier_names TEXT,
  networks TEXT,
  bucket TEXT,
  n_msas BIGINT,
  seg_pop BIGINT,
  gy9 NUMERIC,
  gy8 NUMERIC,
  gyd NUMERIC,
  cb9 NUMERIC,
  cb8 NUMERIC,
  cbd NUMERIC,
  red9 NUMERIC,
  red8 NUMERIC,
  miss9 NUMERIC,
  miss8 NUMERIC,
  rate9 BIGINT,
  rank9 BIGINT,
  n_rates_gy9 BIGINT,
  n_green9 BIGINT,
  n_yellow9 BIGINT,
  n_red9 BIGINT,
  n_notassigned9 BIGINT,
  pct_medicare9 NUMERIC,
  n_hosp_in_plan9 BIGINT,
  n_hosp_universe BIGINT,
  pct_hosp9 NUMERIC
);
ALTER TABLE ccm_region ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated read" ON ccm_region FOR SELECT TO authenticated USING (true);

DROP TABLE IF EXISTS ccm_state CASCADE;
CREATE TABLE ccm_state (
  id BIGSERIAL PRIMARY KEY,
  state TEXT,
  carrier TEXT,
  plan_ids TEXT,
  carrier_names TEXT,
  networks TEXT,
  bucket TEXT,
  n_msas BIGINT,
  seg_pop BIGINT,
  gy9 NUMERIC,
  gy8 NUMERIC,
  gyd NUMERIC,
  cb9 NUMERIC,
  cb8 NUMERIC,
  cbd NUMERIC,
  red9 NUMERIC,
  red8 NUMERIC,
  miss9 NUMERIC,
  miss8 NUMERIC,
  rate9 BIGINT,
  rank9 BIGINT,
  n_rates_gy9 BIGINT,
  n_green9 BIGINT,
  n_yellow9 BIGINT,
  n_red9 BIGINT,
  n_notassigned9 BIGINT,
  pct_medicare9 NUMERIC,
  n_hosp_in_plan9 BIGINT,
  n_hosp_universe BIGINT,
  pct_hosp9 NUMERIC
);
ALTER TABLE ccm_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated read" ON ccm_state FOR SELECT TO authenticated USING (true);

DROP TABLE IF EXISTS ccm_county CASCADE;
CREATE TABLE ccm_county (
  id BIGSERIAL PRIMARY KEY,
  county_code BIGINT,
  county_name TEXT,
  state TEXT,
  carrier TEXT,
  plan_ids TEXT,
  carrier_names TEXT,
  networks TEXT,
  bucket TEXT,
  gy_rate9 BIGINT,
  gy_rate8 BIGINT,
  gy_rated BIGINT,
  rank9 BIGINT,
  n_rates_gy9 BIGINT,
  n_rates_gy8 BIGINT,
  n_npi_gy9 BIGINT,
  n_npi_gy8 BIGINT,
  n_hosp_gy9 BIGINT,
  n_hosp_gy8 BIGINT,
  n_hosp_universe BIGINT,
  pct_hosp9 NUMERIC,
  n_codes_gy9 BIGINT,
  n_codes_gy8 BIGINT,
  pct_codebasket_codes9 NUMERIC,
  pct_codebasket_codes8 NUMERIC,
  pct_codebasket_codesd NUMERIC,
  src_carrier_pct9 NUMERIC,
  src_provider_pct9 NUMERIC,
  n_green9 BIGINT,
  n_yellow9 BIGINT,
  n_red9 BIGINT,
  n_notassigned9 BIGINT,
  pct_medicare9 NUMERIC
);
ALTER TABLE ccm_county ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated read" ON ccm_county FOR SELECT TO authenticated USING (true);

DROP TABLE IF EXISTS ccm_msa CASCADE;
CREATE TABLE ccm_msa (
  id BIGSERIAL PRIMARY KEY,
  msa_id BIGINT,
  msa_name TEXT,
  carrier TEXT,
  plan_ids TEXT,
  metadata_plan_ids TEXT,
  carrier_names TEXT,
  networks TEXT,
  plan_status TEXT,
  bucket TEXT,
  state TEXT,
  seg_pop TEXT,
  total_pop BIGINT,
  ooa BIGINT,
  gy9 NUMERIC,
  gy8 NUMERIC,
  gyd NUMERIC,
  cb9 NUMERIC,
  cb8 NUMERIC,
  cbd NUMERIC,
  red9 NUMERIC,
  red8 NUMERIC,
  miss9 NUMERIC,
  miss8 NUMERIC,
  rate9 BIGINT,
  rank9 BIGINT,
  cnt_rate_mrf9 BIGINT,
  cnt_rate_imputed9 BIGINT,
  n_npi_gy9 BIGINT,
  n_codes_gy9 BIGINT,
  n_rates_gy9 BIGINT,
  src_carrier_pct9 NUMERIC,
  src_provider_pct9 NUMERIC,
  src_imputed_pct9 NUMERIC,
  n_green9 BIGINT,
  n_yellow9 BIGINT,
  n_red9 BIGINT,
  n_notassigned9 BIGINT,
  pct_medicare9 NUMERIC,
  n_hosp_in_plan9 BIGINT,
  n_hosp_universe TEXT,
  pct_hosp9 TEXT,
  anchor_carrier_plan_name TEXT,
  anchor_rate9 BIGINT,
  pct_diff_from_anchor9 NUMERIC,
  outlier_check9 BIGINT
);
ALTER TABLE ccm_msa ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated read" ON ccm_msa FOR SELECT TO authenticated USING (true);

DROP TABLE IF EXISTS ccm_hospital CASCADE;
CREATE TABLE ccm_hospital (
  id BIGSERIAL PRIMARY KEY,
  hospital_npi BIGINT,
  hospital_name TEXT,
  ccn_number TEXT,
  city TEXT,
  state TEXT,
  msa_id BIGINT,
  msa_cbsa_name TEXT,
  county_code BIGINT,
  county_name TEXT,
  hospital_mrf_ingested BIGINT,
  carrier TEXT,
  plan_ids TEXT,
  carrier_names TEXT,
  networks TEXT,
  plan_status TEXT,
  bucket TEXT,
  has_plan_data BIGINT,
  ooa BIGINT,
  gy_rate9 BIGINT,
  gy_rate8 BIGINT,
  gy_rated BIGINT,
  rank9 BIGINT,
  n_rates_gy9 BIGINT,
  n_rates_gy8 BIGINT,
  n_codes_gy9 BIGINT,
  n_codes_gy8 BIGINT,
  pct_codebasket_codes9 NUMERIC,
  pct_codebasket_codes8 NUMERIC,
  pct_codebasket_codesd NUMERIC,
  src_carrier_pct9 BIGINT,
  src_provider_pct9 BIGINT,
  n_green9 BIGINT,
  n_yellow9 BIGINT,
  n_red9 BIGINT,
  n_notassigned9 BIGINT,
  pct_medicare9 NUMERIC,
  source_versions9 TEXT
);
ALTER TABLE ccm_hospital ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated read" ON ccm_hospital FOR SELECT TO authenticated USING (true);
